# Generated by Django 5.2.14 on 2026-09-01 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0009_document_slide_error_document_slide_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi', models.CharField(max_length=1000)),
                ('chapter', models.CharField(blank=True, max_length=200)),
                ('excerpt', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='knowledge.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epub_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'document'], name='reading_boo_user_id_b90e2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'document', 'cfi'), name='reading_bookmark_unique_cfi')],
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi', models.CharField(max_length=1000)),
                ('text', models.TextField(blank=True)),
                ('chapter', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(choices=[('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('pink', 'pink'), ('purple', 'purple')], default='yellow', max_length=16)),
                ('style', models.CharField(choices=[('highlight', 'highlight'), ('underline', 'underline')], default='highlight', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='knowledge.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epub_highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'document'], name='reading_hig_user_id_8c7c81_idx')],
            },
        ),
    ]
