# Generated by Django 5.2.14 on 2026-09-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='style',
            field=models.CharField(choices=[('highlight', 'highlight'), ('underline', 'underline'), ('squiggly', 'squiggly')], default='highlight', max_length=16),
        ),
    ]
