# Generated by Django 5.2.14 on 2026-09-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0002_highlight_style_squiggly'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='selector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='cfi',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
