# Generated by Django 5.2 on 2026-09-03 — palette extended with red / orange.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_highlight_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='color',
            field=models.CharField(
                choices=[
                    ('yellow', 'yellow'),
                    ('green', 'green'),
                    ('blue', 'blue'),
                    ('pink', 'pink'),
                    ('purple', 'purple'),
                    ('red', 'red'),
                    ('orange', 'orange'),
                ],
                default='yellow',
                max_length=16,
            ),
        ),
    ]
