# Generated by Django 5.2.14 on 2026-09-08 08:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_conversionjob_slide_status'),
        ('reading', '0004_highlight_color_red_orange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookmark',
            name='reading_bookmark_unique_cfi',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='cfi',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('page__isnull', True)), fields=('user', 'document', 'cfi'), name='reading_bookmark_unique_cfi'),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(condition=models.Q(('page__isnull', False)), fields=('user', 'document', 'page'), name='reading_bookmark_unique_page'),
        ),
    ]
