# Generated by Django 5.2.14 on 2026-09-08 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0010_conversionjob_slide_status'),
        ('reading', '0005_bookmark_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi', models.CharField(blank=True, default='', max_length=1000)),
                ('fraction', models.FloatField(blank=True, null=True)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('offset', models.FloatField(blank=True, null=True)),
                ('slide', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_positions', to='knowledge.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-updated_at'], name='reading_rea_user_id_ae0da6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'document'), name='reading_position_unique_user_doc')],
            },
        ),
    ]
