# Generated by Django 5.2.14 on 2026-05-17 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='knowledge.document')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='knowledge.document')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['target'], name='linking_doc_target__999c0f_idx'), models.Index(fields=['source'], name='linking_doc_source__f5d6e0_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'position'), name='unique_link_at_position')],
            },
        ),
    ]
