# Generated by Django 5.2.14 on 2026-05-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(default='claude-opus-4-7', help_text='缺省调用的 Claude 模型 ID', max_length=80)),
                ('enabled', models.BooleanField(default=True, help_text='主开关；关闭后所有 AI endpoint 返回 503')),
                ('max_tokens', models.PositiveIntegerField(default=1024, help_text='单次调用允许的最大 output token 数')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI 设置',
                'verbose_name_plural': 'AI 设置',
            },
        ),
    ]
