# Generated by Django 5.2.14 on 2026-05-30 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_aiusagelog"),
        ("knowledge", "0005_kb_category_doc_sort_favorites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, help_text="首条用户消息前 60 字", max_length=120),
                ),
                (
                    "messages",
                    models.JSONField(
                        default=list,
                        help_text="[{role: user|assistant, content: str, ts: ISO}, ...]",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="菜单显示名 · 60 字内", max_length=60)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="✨",
                        help_text="单字符 emoji，用于菜单图标",
                        max_length=10,
                    ),
                ),
                (
                    "instruction",
                    models.TextField(help_text="发给 AI 的指令模板，会与用户当前选区拼接"),
                ),
                (
                    "requires_selection",
                    models.BooleanField(default=True, help_text="是否需要先选中文字才能用"),
                ),
                (
                    "replace_mode",
                    models.CharField(
                        choices=[
                            ("none", "仅显示，不替换"),
                            ("replace", "替换选中"),
                            ("before", "插入到上方"),
                            ("after", "插入到下方"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, help_text="排序权重，越大越靠前")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="aisettings",
            name="daily_budget_usd_per_user",
            field=models.FloatField(
                default=0.0, help_text="每用户每日预算（USD）。0 = 不限。超出后调用返回 429。"
            ),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="enable_thinking",
            field=models.BooleanField(
                default=False,
                help_text="Claude 4 extended thinking：开启后难题用扩展推理（贵但准）",
            ),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="fallback_enabled",
            field=models.BooleanField(
                default=True, help_text="调用失败（限流/超时）时自动降级到下一档模型"
            ),
        ),
        migrations.AddField(
            model_name="aiusagelog",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="knowledge.document",
            ),
        ),
        migrations.AddField(
            model_name="aiusagelog",
            name="fallback_from",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="aiusagelog",
            name="knowledge_base",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="knowledge.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="aiusagelog",
            name="prompt_chars",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="aisettings",
            name="default_model",
            field=models.CharField(
                default="claude-opus-4-7",
                help_text="缺省调用的模型 ID（Claude 或 Qwen）",
                max_length=80,
            ),
        ),
        migrations.AddIndex(
            model_name="aiusagelog",
            index=models.Index(
                fields=["user", "created_at"], name="ai_aiusagel_user_id_e34bca_idx"
            ),
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="knowledge.document",
            ),
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiprompttemplate",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_prompt_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="ai_aiconver_user_id_fe4cc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiprompttemplate",
            index=models.Index(fields=["owner", "-order"], name="ai_aiprompt_owner_i_444a8b_idx"),
        ),
    ]
