# Generated by Django 5.2.14 on 2026-06-07 21:35

from django.db import migrations, models


def backfill_estimated_usd(apps, schema_editor):
    """Compute estimated_usd for existing rows so budget/usage stay accurate
    across the upgrade (new rows compute it at write time)."""
    from apps.ai.pricing import estimate_cost_usd

    AIUsageLog = apps.get_model("ai", "AIUsageLog")
    batch = []
    for row in AIUsageLog.objects.all().iterator(chunk_size=500):
        try:
            row.estimated_usd = float(
                estimate_cost_usd(row.model, row.input_tokens, row.output_tokens)
            )
        except Exception:
            row.estimated_usd = 0.0
        batch.append(row)
        if len(batch) >= 500:
            AIUsageLog.objects.bulk_update(batch, ["estimated_usd"])
            batch = []
    if batch:
        AIUsageLog.objects.bulk_update(batch, ["estimated_usd"])


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_aiconversation_aiprompttemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusagelog",
            name="estimated_usd",
            field=models.FloatField(default=0.0),
        ),
        migrations.RunPython(backfill_estimated_usd, migrations.RunPython.noop),
    ]
