# Generated by Django 5.2.14 on 2026-06-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttask',
            name='selection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='exporttask',
            name='scope',
            field=models.CharField(choices=[('doc', 'Document'), ('folder', 'Folder'), ('kb', 'Knowledge Base'), ('selection', 'Selection')], max_length=10),
        ),
    ]
