# Generated by Django 5.2.14 on 2026-05-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='paper_style',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='accent_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
