# Generated by Django 5.2.14 on 2026-05-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_document_paper_style_knowledgebase_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
