# Generated by Django 5.2.14 on 2026-06-07 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0005_kb_category_doc_sort_favorites"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="document",
            name="knowledge_d_knowled_8f6166_idx",
        ),
        migrations.RemoveIndex(
            model_name="document",
            name="knowledge_d_visibil_994972_idx",
        ),
        migrations.RemoveIndex(
            model_name="folder",
            name="knowledge_f_knowled_700a6e_idx",
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["knowledge_base", "folder", "is_deleted"],
                name="knowledge_d_knowled_62c49d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["visibility", "status", "is_deleted", "-published_at"],
                name="knowledge_d_visibil_564ad2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["knowledge_base", "parent", "is_deleted"],
                name="knowledge_f_knowled_10990d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgebase",
            index=models.Index(
                fields=["owner", "is_deleted", "order"], name="knowledge_k_owner_i_94a8e7_idx"
            ),
        ),
    ]
