# Generated by Django 5.2.14 on 2026-06-26 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usertag'),
        ('knowledge', '0006_remove_document_knowledge_d_knowled_8f6166_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='audience_mode',
            field=models.CharField(choices=[('all', '全员可见'), ('exclude', '部分不可见'), ('include', '仅部分可见')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='audience_tags',
            field=models.ManyToManyField(blank=True, related_name='+', to='accounts.usertag'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='audience_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgebasecategory',
            name='audience_mode',
            field=models.CharField(choices=[('all', '全员可见'), ('exclude', '部分不可见'), ('include', '仅部分可见')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='knowledgebasecategory',
            name='audience_tags',
            field=models.ManyToManyField(blank=True, related_name='+', to='accounts.usertag'),
        ),
        migrations.AddField(
            model_name='knowledgebasecategory',
            name='audience_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
