# Generated by Django 5.2.14 on 2026-07-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0007_knowledgebase_audience_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="heading_numbering",
            field=models.BooleanField(default=False),
        ),
    ]
