# Generated by Django 5.2.14 on 2026-07-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0008_document_heading_numbering'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slide_error',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='slide_status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
