# Generated by Django 5.2.14 on 2026-09-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_document_slide_error_document_slide_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slide_status',
            field=models.CharField(blank=True, choices=[('', '—'), ('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='', max_length=10),
        ),
    ]
