# Generated by Django 5.2.14 on 2026-05-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, help_text="主开关；关闭后首页隐藏题记区。"),
                ),
                (
                    "quotes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{id, text, attribution}, …]，由后台维护。",
                    ),
                ),
                (
                    "rotation_seconds",
                    models.PositiveIntegerField(
                        default=8, help_text="多条时每隔多少秒切到下一条。"
                    ),
                ),
                (
                    "animation",
                    models.CharField(
                        choices=[
                            ("fade", "fade"),
                            ("slide", "slide"),
                            ("typewriter", "typewriter"),
                            ("zoom", "zoom"),
                        ],
                        default="fade",
                        help_text="切换动画样式。",
                        max_length=24,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "题记设置",
                "verbose_name_plural": "题记设置",
            },
        ),
    ]
