# Generated by Django 5.2.14 on 2026-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_quote_dynasty'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosettings',
            name='play_order',
            field=models.CharField(choices=[('random', 'random'), ('sequential', 'sequential')], default='random', help_text='播放顺序：random 每次打开页面随机洗牌；sequential 按列表顺序。', max_length=16),
        ),
        migrations.AlterField(
            model_name='herosettings',
            name='animation',
            field=models.CharField(choices=[('fade', 'fade'), ('slide', 'slide'), ('typewriter', 'typewriter'), ('ink-wash', 'ink-wash')], default='fade', help_text='切换动画样式。', max_length=24),
        ),
    ]
