# Generated by Django 5.2.14 on 2026-07-24 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usertag'),
        ('knowledge', '0009_document_slide_error_document_slide_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_grants', to='knowledge.knowledgebasecategory')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_grants', to='knowledge.document')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_grants', to='knowledge.folder')),
                ('knowledge_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_grants', to='knowledge.knowledgebase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('document__isnull', True), ('folder__isnull', True), ('knowledge_base__isnull', False)), models.Q(('category__isnull', False), ('document__isnull', True), ('folder__isnull', True), ('knowledge_base__isnull', True)), models.Q(('category__isnull', True), ('document__isnull', True), ('folder__isnull', False), ('knowledge_base__isnull', True)), models.Q(('category__isnull', True), ('document__isnull', False), ('folder__isnull', True), ('knowledge_base__isnull', True)), _connector='OR'), name='readgrant_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('knowledge_base__isnull', False)), fields=('user', 'knowledge_base'), name='uniq_readgrant_user_kb'), models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('user', 'category'), name='uniq_readgrant_user_category'), models.UniqueConstraint(condition=models.Q(('folder__isnull', False)), fields=('user', 'folder'), name='uniq_readgrant_user_folder'), models.UniqueConstraint(condition=models.Q(('document__isnull', False)), fields=('user', 'document'), name='uniq_readgrant_user_document')],
            },
        ),
    ]
