# Generated by Django 5.2 on 2026-09-03 — site-wide 目录 (TOC) defaults singleton.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_readgrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TocSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefs', models.JSONField(blank=True, default=dict, help_text='目录展示默认值（见 DEFAULT_TOC_PREFS）。')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '目录设置',
                'verbose_name_plural': '目录设置',
            },
        ),
    ]
