# Generated by Django 5.2.14 on 2026-05-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_document_paper_style_knowledgebase_accent_color'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgebase')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='knowledge_bases',
            field=models.ManyToManyField(related_name='tags', through='tags.KnowledgeBaseTag', to='knowledge.knowledgebase'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebasetag',
            constraint=models.UniqueConstraint(fields=('knowledge_base', 'tag'), name='unique_kb_tag'),
        ),
    ]
