# Generated by Django 5.2.14 on 2026-05-18 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_document_paper_style_knowledgebase_accent_color'),
        ('tags', '0002_knowledgebasetag_tag_knowledge_bases_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge.folder')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='folders',
            field=models.ManyToManyField(related_name='tags', through='tags.FolderTag', to='knowledge.folder'),
        ),
        migrations.AddConstraint(
            model_name='foldertag',
            constraint=models.UniqueConstraint(fields=('folder', 'tag'), name='unique_folder_tag'),
        ),
    ]
