# Generated by Django 5.2.14 on 2026-05-17 14:46

import apps.editor.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=apps.editor.models._upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='knowledge.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='editor_atta_documen_8f4935_idx'), models.Index(fields=['uploaded_by', '-created_at'], name='editor_atta_uploade_9064db_idx')],
            },
        ),
    ]
