# Generated by Django 5.2.14 on 2026-07-03 13:18

import apps.editor.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
        ("knowledge", "0008_document_heading_numbering"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlideImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(
                        max_length=500, upload_to=apps.editor.models._slide_upload_path
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="knowledge.document",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slide_images",
                        to="editor.attachment",
                    ),
                ),
            ],
            options={
                "ordering": ["index"],
                "indexes": [
                    models.Index(
                        fields=["document", "index"], name="editor_slid_documen_b7807d_idx"
                    )
                ],
                "unique_together": {("document", "index")},
            },
        ),
    ]
