# Generated by Django 5.2.14 on 2026-07-06 23:55

import apps.editor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_slideimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideimage',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, upload_to=apps.editor.models._slide_upload_path),
        ),
    ]
