# Generated by Django 5.2.14 on 2026-07-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0003_slideimage_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="slideimage",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
