# Generated by Django 5.2.14 on 2026-09-08 07:06

import apps.editor.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_slideimage_notes'),
        ('knowledge', '0009_document_slide_error_document_slide_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deck_pdf', 'Slide deck PDF'), ('ocr_pdf', 'OCR PDF'), ('poster', 'Poster'), ('cover', 'Cover')], max_length=16)),
                ('file', models.FileField(max_length=500, upload_to=apps.editor.models._derived_upload_path)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('size', models.BigIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_files', to='knowledge.document')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_files', to='editor.attachment')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'kind'], name='editor_deri_documen_29baea_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'kind'), name='editor_derivedfile_unique_kind')],
            },
        ),
    ]
