# Generated by Django 5.2.14 on 2026-09-08 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_derivedfile'),
        ('knowledge', '0010_conversionjob_slide_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pptx_slides', 'PPTX → slides'), ('deck_pdf', 'Deck PDF'), ('pdf_extract', 'Text extract'), ('poster', 'Poster'), ('cover', 'Cover'), ('ocr', 'OCR')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='running', max_length=10)),
                ('task_id', models.CharField(blank=True, default='', max_length=64)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('src_bytes', models.BigIntegerField(default=0)),
                ('out_bytes', models.BigIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_jobs', to='knowledge.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'kind'], name='editor_conv_documen_065659_idx'), models.Index(fields=['status', 'created_at'], name='editor_conv_status_c52cf8_idx'), models.Index(fields=['-created_at'], name='editor_conv_created_50d7d4_idx')],
            },
        ),
    ]
