# Generated by Django 5.2.14 on 2026-09-08 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_conversionjob_slide_status'),
        ('knowledge', '0010_conversionjob_slide_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('none', 'None'), ('pdf', 'PDF (pdftotext)'), ('deck_pdf', 'Slide deck PDF'), ('ocr_pdf', 'OCR PDF'), ('epub', 'EPUB')], default='none', max_length=16)),
                ('text', models.TextField(blank=True, default='')),
                ('chars', models.PositiveIntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('encrypted', models.BooleanField(default=False)),
                ('is_scanned', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('extracted_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extract', to='knowledge.document')),
            ],
            options={
                'indexes': [models.Index(fields=['is_scanned'], name='editor_docu_is_scan_aa8878_idx')],
            },
        ),
    ]
